switch the type of Element.id from id to string for R4B
nazrulworld/fhir.resources pull request #160
Opened 2024-07-26 12:32 UTC by cybernop

According to the FHIR documentation `Element.id` should be of type `string`.

StructureDefinitions with type slicing will have entries in the differential and snapshot part in the format  like `Observation.category:VSCat`. This is valid according to the specification. But before the element was of type `id` which caused validation errors when parsing StructureDefinitions like this.

2024-07-28 08:45 UTC, nazrulworld commented
@cybernop please have a look here https://github.com/nazrulworld/fhir.resources?tab=readme-ov-file#resourceid-aka-fhirtypesid-constraint-extensibility

2024-07-29 05:52 UTC, cybernop commented
> @cybernop Thanks a lot for your PR. Please have a look here https://github.com/nazrulworld/fhir.resources?tab=readme-ov-file#resourceid-aka-fhirtypesid-constraint-extensibility
> 
> Here is an example of patch https://github.com/nazrulworld/fhir.resources/blob/main/fhir/resources/core/patch/patch_r4b_test.py

@nazrulworld Thanks for the reply. But I do not fully understand what you are trying to tell me. Do you want to tell me error is on the user side or should should I add a test case? I do not want to to change the length of Id nor do I want to create a patch for something. I just wanted to fix an error in the data type definition.

In my opinion the type of `Element.id` in R4B is incorrect. In the definition it is of type `string` and all other version (DSTU2, STU3 and R5) use the correct data type for `Element.id`. Only in R4B `id` was used incorrectly which prevents using the library in my project because of invalid parsing errors.

2024-08-12 14:23 UTC, cybernop commented
I just want to stress that this is an issue of incorrect type and not the length of ID

2024-10-23 09:48 UTC, Horstage commented
That's especially annoying since it's only the case for [R4B](https://github.com/nazrulworld/fhir.resources/blob/7.1.0/fhir/resources/R4B/element.py#L45), not for [DSTU2](https://github.com/nazrulworld/fhir.resources/blob/7.1.0/fhir/resources/DSTU2/element.py#L30), [STU3](https://github.com/nazrulworld/fhir.resources/blob/7.1.0/fhir/resources/STU3/element.py#L46) or [R5](https://github.com/nazrulworld/fhir.resources/blob/7.1.0/fhir/resources/element.py#L43).
The [FHIR definition for Elements](https://www.hl7.org/fhir/r4b/element-definitions.html#def) states, that `Element.id` is a string in all versions.

2024-10-23 12:06 UTC, Horstage requested changes
Types have changed in f604fb196485fde39c95244016be3a1a91e5a0b8.
It is now `StringType`

2024-10-23 14:58 UTC, cybernop commented
Updated the type to use the new `StringType`

2024-10-23 15:01 UTC, cybernop commented
I want to stress how important this issue is, as in Germany we only use R4(B) at the moment and this issue prevents us to use the library for any StructureDefinition

2024-10-23 19:08 UTC, nazrulworld commented
@cybernop PR should be merge with the branch 7.X.X, right?

2024-10-24 07:47 UTC, Horstage commented
I took the liberty to create a separate PR #165 for 7.x.x as it should be fixed in both 7.x.x and main, but the commits differ slightly.

2024-10-24 08:09 UTC, cybernop commented on fhir/resources/R4B/element.py
> +    id: fhirtypes.StringType = Field(
Yes you are right, I adjusted my PR

2024-10-24 08:12 UTC, cybernop commented
@nazrulworld This change should be merged into main

2024-10-24 08:26 UTC, merged

2024-10-24 19:22 UTC, nazrulworld commented
This new release should have been your PR included https://pypi.org/project/fhir.resources/8.0.0b4/